### PR TITLE
Fix various bugs in MOIwrapper.jl

### PR DESCRIPTION
**Pull request by odow**
Here are a few fixes for the MOI wrapper that should get more tests passing

### CODE REVIEW

**Comment by PharosAbad** [comment]
Is it possible to exclude `MOI.ConstraintDual` ?

https://github.com/odow/StatusSwitchingQP.jl/blob/patch-3/test/testMOI.jl#L198

it seems it is not exclude

**Comment by odow** [comment]
Do you have an example of where the test is failing because of a call to `ConstraintDual`? This does exclude `ConstraintDual` related tests

**Comment by PharosAbad** [comment]
thanks very much for your help!

now reach  https://github.com/PharosAbad/StatusSwitchingQP.jl/commit/88600a530699f31105a348846a547ccd19ffef1f  and https://github.com/PharosAbad/StatusSwitchingQP.jl/actions/runs/5020718612/jobs/9002438585

```
Test Summary: | Pass  Total     Time
MOI           | 1120   1120  4m07.7s
```

I pre-solve the "invalid" model to meet the requirement of the MOI.

**Comment by odow** [comment]
Nice work! That's looking a lot better.

Can you try removing this exclude? It should work now:
https://github.com/PharosAbad/StatusSwitchingQP.jl/blob/88600a530699f31105a348846a547ccd19ffef1f/test/testMOI.jl#L214

The tests are looking a lot healthier, but I'd still encourage you to get the package working and tested on Julia 1.6. Otherwise people installing on Julia 1.6 will end up with an old version that still contains all of the bugs.

**Comment by PharosAbad** [comment]
thanks again

`test_model_supports_constraint_ScalarAffineFunction_EqualTo` test passed

**Pull request closed without merging**
